[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "W", "PERF", "PT", "PL"]

[tool.ruff.lint.isort]
known-first-party = ["utils", "memory", "config"]
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]