[tool.ruff]
line-length = 100
target-version = "py311"  # or your runtime

[tool.ruff.lint]
select = [
  "E",   # pycodestyle (incl. E402, E501)
  "F",   # pyflakes (incl. F811)
  "PLC", # pylint-convention (incl. PLC0415)
  "PLR", # pylint-refactor (incl. PLR0913)
]
ignore = [
  # add any conscious exceptions here
]

[tool.ruff.lint.per-file-ignores]
# If you decide to allow imports inside tests (often okay for fixtures):
"tests/test_*.py" = ["PLC0415"]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"